

services:
  app:
    build: .
    container_name: aws-sage-maker
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8502:8080"
      - "5001:5000"
    command: python3 app.py #uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    #entrypoint: bash -c "set -a && source .env && exec bash"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  lab:
    image: jupyter/minimal-notebook:python-3.11
    ports: ["8888:8888"]
    volumes:
      - ./:/home/jovyan/work
    command: start-notebook.sh # --NotebookApp.token=''   remove for token auth
   
